export const contactInfo = {
  australia: {
    image:"./src/assets/sydney-image.jpg",
    name: "Sydney Opera House",
    line1: "Bennelong Point, Sydney NSW 2000, Australia",
    founded:"October 20, 1973",
    description:"The Sydney Opera House is an iconic performing arts center located in Sydney, Australia. Famous for its unique sail-like design, it is one of the most recognizable and photographed buildings in the world. The venue hosts a diverse range of performances, including opera, ballet, and concerts, and is a masterpiece of modern architecture and engineering.",
    website: "#",
    landmarkType:'Performance Arts',
    interested1:'Forbidden City',
    interested2:'Temple of Heaven',
    interested3:'Jingshan Park',
    interested4:'Beijing City Fortification',
    imageInterested1:'./src/assets/china/forbiddenCity.jpeg',
    imageInterested2:'./src/assets/china/templeofHeaven.jpeg',
    imageInterested3:'./src/assets/china/jingshanPark.jpeg',
    imageInterested4:'./src/assets/china/beijingCityFortification.jpeg'
  },
  china: {
    image:"./src/assets/china-image.jpg",
    name: "The Great Wall of China",
    line1: "Huairou District, Beijing, China",
    founded:"220 BC",
    description:"The Great Wall of China is an ancient fortification that stretches over 13,000 miles across northern China. Built to protect against invasions, it is one of the most impressive architectural feats in history. Constructed from various materials including earth, wood, and stone, the wall offers breathtaking views and is a symbol of China's rich historical heritage.",
    website: "#",
    landmarkType:'Historical Monument',
    interested1:'Forbidden City',
    interested2:'Temple of Heaven',
    interested3:'Jingshan Park',
    interested4:'Beijing City Fortification',
    imageInterested1:'./src/assets/china/forbiddenCity.jpeg',
    imageInterested2:'./src/assets/china/templeofHeaven.jpeg',
    imageInterested3:'./src/assets/china/jingshanPark.jpeg',
    imageInterested4:'./src/assets/china/beijingCityFortification.jpeg'
  },
  singapore: {
    image:"./src/assets/singapore-image.jpg",
    name: "Merlion",
    line1: "Merlion Park, Singapore",
    founded: "1964",
    description: "The Merlion is a mythical creature that symbolizes Singapore, featuring the head of a lion and the body of a fish. Located at Marina Bay, it represents Singapore’s origins as a fishing village and its transformation into a global city. The statue stands at 8.6 meters tall and is a popular tourist attraction, offering views of the city skyline and harbor.",
    website: "#",
    landmarkType:'Statue by Lim Nang Seng',
    interested1:'Sydney Harbour Bridge',
    interested2:'Port Jackson Bay',
    interested3:'Darling Harbour',
    interested4:'Bondi Beach',
    imageInterested1:'./src/assets/australia/harbourBridge.jpeg',
    imageInterested2:'./src/assets/australia/portJackson.jpeg',
    imageInterested3:'./src/assets/australia/darling.jpeg',
    imageInterested4:'./src/assets/australia/bondi.jpeg'
  },
};